### ISSUE TITLE
Buy lifebelt

### ISSUE THREAD

**Issue by mbalamat** [ellak-monades-aristeias/droneLifeguard#4]
We have to buy a lifebelt that is almost the same size as the base of the frame of the quadcopter that is roughly 30cm in diameter.

**Comment by BillyTziv** [comment]
Have in mind the the diameter and the weight of the lifebelt is depending on the craft. A Hexacopter or Octacopter can lift a bigger lifebelt or more than one of the same size.

**Comment by mbalamat** [comment]
OK we have to experiment on this maybe going with the frame to shop?

**Comment by mbalamat** [comment]
ok we have come up with the solution.
