### ISSUE TITLE
Not enough channels

### ISSUE THREAD

**Issue by BillyTziv** [ellak-monades-aristeias/droneLifeguard#6]
Our receiver does not support 5 channels and we should devise a way to bypass the fifth channel. this is necessary for motor arming.

**Comment by mbalamat** [comment]
How does a 6 channel receiver cost and how fast can we get it?
Or do you propose a workaround?

**Comment by BillyTziv** [comment]
40 euros and we can get it in 1 month. so it is not an option.

**Comment by mbalamat** [comment]
ok then it will be a workaround, do you have any other remote transceiver
of any kind?

Στις Παρ, 2 Οκτ 2015 στις 7:11 μ.μ., ο/η Vasilis Tzivaras <
notifications@github.com> έγραψε:

**Comment by BillyTziv** [comment]
no but i think that i made it work. we can bypass the fifth channel by assigning also the 5th channel to rudder.

**Comment by mbalamat** [comment]
ACK!

Στις Παρ, 2 Οκτ 2015 στις 10:25 μ.μ., ο/η Vasilis Tzivaras <
notifications@github.com> έγραψε:
