### ISSUE TITLE
Motor Calibration

### ISSUE THREAD

**Issue by BillyTziv** [ellak-monades-aristeias/droneLifeguard#7]
For some reason motors do not spin at the same RPM. As a result, there is a huge drag that have to be eliminated somehow. The plan is to calibrate manually all the ESC through the transmitter.

**Comment by mbalamat** [comment]
ok so this is on you I will design the payload delivery mechanism.

Στις Σάβ, 3 Οκτ 2015 στις 1:58 π.μ., ο/η Vasilis Tzivaras <
notifications@github.com> έγραψε:

**Comment by mbalamat** [comment]
When you finish close the issue.

Στις Σάβ, 3 Οκτ 2015 στις 5:01 π.μ., ο/η Mario Balamatsias <
mbalamatsias@gmail.com> έγραψε:
